In [1]:
import numpy as np
import random
import math
from matplotlib import pyplot as plt
from sklearn.datasets.samples_generator import make_blobs
import time
import pandas as pd
from scipy.spatial.distance import cdist
from sklearn.utils import shuffle
# from sklearn.cluster import KMeans
import numpy as np
import kmeansAlgo as k
from sklearn.cluster import SpectralClustering

from sklearn.preprocessing import LabelEncoder
from sklearn.utils import shuffle
np.random.seed(0)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:143: FutureWarning: The sklearn.datasets.samples_generator module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.datasets. Anything that cannot be imported from sklearn.datasets is now part of the private API.
  warnings.warn(message, FutureWarning)

Initialize the data points and Random centers
===========================

KMeans - Clustering
===============

In [2]:
cluster=8
data=pd.read_csv('qsar_oral_toxicity.csv', header=None, sep=';')  
datasetname='ecoli'
x= np.asarray(data.iloc[:, :-1]) 
y= np.asarray(data.iloc[:, -1]) 
le=LabelEncoder()
y=le.fit_transform(y)
cluster=np.unique(y).shape[0] 
data.head()

,0,1,2,3,4,5,6,7,8,9,...,1015,1016,1017,1018,1019,1020,1021,1022,1023,1024
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,negative
1,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,negative
2,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,negative
3,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,negative
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,negative

In [3]:
for i in range(10):
    
    data=shuffle(data)
    x= np.asarray(data.iloc[:, :-1]) 
    y= np.asarray(data.iloc[:, -1]) 
    le=LabelEncoder()
    y=le.fit_transform(y)
    

    clustering = SpectralClustering(n_clusters=cluster, affinity='nearest_neighbors' ,
                                    gamma=1,  assign_labels="discretize", random_state=0)
    clustering.fit(x) 
    ny=clustering.labels_   
        
    mypred=pd.DataFrame()
    mypred['Actual']=y
    mypred['Predicted']=ny
    
    mypred.to_csv('SpectralClustering_'+str(i)+'_pred.txt',sep=',',index=False)
    print(i)

0
1
2
3
4
5
6
7
8
9