In [1]:
import numpy as np
import random
import math
from matplotlib import pyplot as plt
from sklearn.datasets.samples_generator import make_blobs
import time
import pandas as pd
from scipy.spatial.distance import cdist
from sklearn.utils import shuffle
# from sklearn.cluster import KMeans
import numpy as np
import kmeansAlgo as k
from sklearn.cluster import AgglomerativeClustering

from sklearn.preprocessing import LabelEncoder
from sklearn.utils import shuffle
np.random.seed(0)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:143: FutureWarning: The sklearn.datasets.samples_generator module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.datasets. Anything that cannot be imported from sklearn.datasets is now part of the private API.
  warnings.warn(message, FutureWarning)

Initialize the data points and Random centers
===========================

AgglomerativeClustering - Clustering
===============

In [2]:
cluster=3
# data=pd.read_csv('raw_pe_images.csv', header=0, sep=',')  #
data=pd.read_csv('csv_result-Training Dataset.csv', header=0, sep=',')
datasetname='iris'
x= np.asarray(data.iloc[:, 1:-1]) 
y= np.asarray(data.iloc[:, -1]) 
le=LabelEncoder()
y=le.fit_transform(y) 
cluster=np.unique(y).shape[0]
data.tail()

,id,having_IP_Address,URL_Length,Shortining_Service,having_At_Symbol,double_slash_redirecting,Prefix_Suffix,having_Sub_Domain,SSLfinal_State,Domain_registeration_length,...,popUpWidnow,Iframe,age_of_domain,DNSRecord,web_traffic,Page_Rank,Google_Index,Links_pointing_to_page,Statistical_report,Result
11050,11051,1,-1,1,-1,1,1,1,1,-1,...,-1,-1,1,1,-1,-1,1,1,1,1
11051,11052,-1,1,1,-1,-1,-1,1,-1,-1,...,-1,1,1,1,1,1,1,-1,1,-1
11052,11053,1,-1,1,1,1,-1,1,-1,-1,...,1,1,1,1,1,-1,1,0,1,-1
11053,11054,-1,-1,1,1,1,-1,-1,-1,1,...,-1,1,1,1,1,-1,1,1,1,-1
11054,11055,-1,-1,1,1,1,-1,-1,-1,1,...,1,1,-1,1,-1,-1,-1,1,-1,-1

In [3]:
for i in range(10):
    
    data=shuffle(data)
    x= np.asarray(data.iloc[:, 1:-1]) 
    y= np.asarray(data.iloc[:, -1]) 
    le=LabelEncoder()
    y=le.fit_transform(y) 
    
    clustering = AgglomerativeClustering(n_clusters = cluster,linkage= "single")  
    clustering.fit(x) 
    
    ny=clustering.labels_  
        
    mypred=pd.DataFrame()
    mypred['Actual']=y
    mypred['Predicted']=ny
    
    mypred.to_csv('AgglomerativeClustering_'+str(i)+'_pred.txt',sep=',',index=False)
    print(i)

0
1
2
3
4
5
6
7
8
9