In [1]:
import pandas as pd
import numpy as np

In [3]:
data1=pd.read_csv('APCOS_0_pred.txt');
data1

     Actual  Predicted
0         1          2
1         2          0
2         2          2
3         0          1
4         2          0
5         1          2
6         0          1
7         1          2
8         0          1
9         1          2
10        1          2
11        2          2
12        2          0
13        2          0
14        0          1
15        0          1
16        2          2
17        2          0
18        0          1
19        0          1
20        1          2
21        2          0
22        0          1
23        1          2
24        1          2
25        2          0
26        1          2
27        1          2
28        1          2
29        2          0
..      ...        ...
120       2          0
121       1          2
122       2          0
123       0          1
124       2          0
125       0          1
126       2          0
127       0          1
128       1          2
129       0          1
130       2          0
131       2          0
132       0          1
133       2          2
134       2          2
135       2          0
136       1          2
137       0          1
138       1          2
139       0          1
140       0          1
141       1          2
142       2          2
143       0          1
144       2          0
145       0          1
146       1          2
147       2          0
148       2          0
149       1          2

[150 rows x 2 columns]

In [5]:
data1.groupby(by=['Actual','Predicted']).size()

Actual  Predicted
0       1            50
1       0             2
        2            48
2       0            36
        2            14
dtype: int64